-- SQL Schema for Supabase 'kandidat' table

CREATE TABLE IF NOT EXISTS kandidat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama TEXT NOT NULL,
    skor INT NOT NULL,
    akurasi INT NOT NULL,
    jawaban JSONB,
    is_correct JSONB,
    violation_count INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE kandidat ENABLE ROW LEVEL SECURITY;

-- Allow anyone to insert (public submission)
CREATE POLICY "Allow public insert" ON kandidat
    FOR INSERT 
    WITH CHECK (true);

-- Allow anyone to read (optional, or restrict to authenticated)
CREATE POLICY "Allow public read" ON kandidat
    FOR SELECT
    USING (true);
